config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :models, only: %i[index]
end

app/models/make.rb
class Make < ActiveRecord::Base
  has_many :models
end

app/models/model.rb
class Model < ActiveRecord::Base
  belongs_to :make

  validates :name, :make_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @makes = Make.all

    SearchMakes.fetch
  end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  def index
    @models = Model.all
    SearchModels.fetch(params[:webmotors_make_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def make_options
    Make.all.map{ |u| [ u.name, u.webmotors_id ] }
  end
end

app/views/home/index.html.erb
<%= form_tag(models_path, method: :get) do %>
  <%= select_tag "webmotors_make_id", options_for_select(make_options) %>
  <%= submit_tag "Buscar modelos", data: { disable_with: "Buscando..." } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdtsysApplicantTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/models/index.html.erb
<a href="/"><< Voltar</a>
<ul>
  <% @models.each do |model| %>
    <li><%= model.name %></li>
  <% end %>
</ul>